### ISSUE TITLE
JOSE submission roadmap

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/paper-rcourse#14]
We can prepare a submission to the [Journal of Open Source Education](https://jose.theoj.org/about#about) pretty simply. Our course falls under the *learning module* category of *open educational materials*. Luke and I think it can be done in about 2 days. 

Here's an overview of what needs to happen:

* [x] #38 Update the rcourse README, using some of the text we generate here.
* [x] #17 Add an [OSI-approved license](https://opensource.org/licenses/alphabetical) for the code components of the course (add to LICENSE.md in the course repo). 
* [x] Create `paper.md` following the JOSE guidelines below - about 1000 words total (2 ish pages)
    * [x] List all authors and affiliations.
    * [x] Describe the submission, and explain its eligibility for JOSE (#36) .
    * [x] #18 Include a _Statement of Need_, explaining how the submitted artifacts contribute to computationally enabled teaching and learning, and describing how they might be adopted by others.
   * [x] For learning modules, describe:
        * [x] the learning objectives and content (#30) 
        * [x] instructional design (#35). Instructional design of the module should be intentional and apparent. For example, the weaving of text, images, code and output might apply the [worked-example effect](https://en.wikipedia.org/wiki/Worked-example_effect), deliberately. The authors should briefly explain their design in the JOSE paper. 
        * [x] experience of use in teaching and learning situations (#28). 
   * [x] #27 Tell us the "story" of the project: how did it come to be?
   * [x] List key references including a link to the course repo (#43) .
* [x] #37 Create a metadata file for the repo - they have a [script](https://gist.github.com/arfon/478b2ed49e11f984d6fb) to auto-generate it.
* [x] Upload `paper.md` and `paper.bib` to `rcourse` repository.
* [x] Submit via the [JOSE web app](http://jose.theoj.org/).

Example `paper.md` from the [JOSE website](https://jose.theoj.org/about#about):

```
---
title: 'Fidgit: An ungodly union of GitHub and figshare'
tags:
- example
- tags
- for the paper
authors:
- name: Arfon M Smith
  orcid: 0000-0000-0000-1234
  affiliation: "1, 2" # (Multiple affiliations must be quoted)
- name: Mickey Mouse
  orcid: 0000-0000-0000-1234
  affiliation: 2
affiliations:
- name: Space Telescope Science Institute
  index: 1
- name: Disney Inc.
  index: 2
date: 14 February 2016
bibliography: paper.bib
---

# Summary

Lorem ipsum ...

Citations to entries in paper.bib should be in
[rMarkdown](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)
format.

This is an example citation [@figshare_archive].

Figures can be included like this: ![Fidgit deposited in figshare.](figshare_article.png)

# References
```

**Comment by lwjohnst86** [comment]
Submitted!! https://jose.theoj.org/papers/1a083e69c49c15011f9404dfab9b1ec8

Seems it might take some time. Fingers crossed for a quick turn around :)
