### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/paper-rcourse#7]
An outline of the task list timeline.

**Deliverables**:
 * [ ] #4 Preprint on biorxiv
 * [ ] #3 Submit to journal
 * [x] [Completed course with DOI](https://zenodo.org/record/1117433#.WrAGwnXwZhw)
* [ ] Second round of course with DOI

**Short term (1-4 weeks)**:
 * [x] #1 Overall topic and pitch
 * [ ] #5 **Started** Start assembling supplementary information: resources, links, extra analysis, survey results, etc.
* [ ] #8 **Started** Draft outline of paper, major headers/themes (depends on how we structure the paper of course)
* [ ] Results section: bullet point list of major findings / points to make
* [ ] Conclusions section: summary of main points
* [ ] Everyone: read some of the example papers in #5 to get some ideas 

**Medium term (2-3 months)**:
 * [ ] Flesh out results
 * [ ] Discussion
 * [ ] Introduction & literature review
 * [ ] Abstract
 * [ ] Consult with Asher / Martin / Christie

**Long term (~6 months)**:
 * [ ] Editing

**Comment by lwjohnst86** [comment]
Great idea, really like it!! :) +1
